development:
  bucket: yourapp_dev
  access_key_id: AAAAAAAAAAAAAAAAAAA
  secret_access_key: AJHKHJKKJHKHkjsdf+EuXQu5xvingQXY0M+gyYnFGqUJ

test:
  bucket: yourapp_test
  access_key_id: AAAAAAAAAAAAAAAAAAA
  secret_access_key: AJHKHJKKJHKHkjsdf+EuXQu5xvingQXY0M+gyYnFGqUJ

production:
  bucket: antz
  access_key_id: AKIAIAZ7FYZ3A7WS2EFQ
  secret_access_key: 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
